name: Build and test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: dotnet build --configuration Release --output /var/build
      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: /var/build
  test:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 3
    steps:
      - name: Download build result
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Test
        run: dotnet test --configuration Release --no-build /var/build
