on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 3
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Verify commit exists in origin/main
                run: git branch --remote --contains | grep origin/main
            -   name: Extract release notes
                run: |
                    git log --pretty=format:'%d %s' ${GITHUB_REF} | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-preview\d{3})?)(, .*?)*\)|\n## \1\n|g' > RELEASE-NOTES
            -   name: Set VERSION variable from tag
                run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
            -   name: Build
                run: dotnet build --configuration Release /p:Version=${VERSION}
            -   name: Test
                run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
            -   name: Pack
                run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
            -   name: Publish artifacts
                uses: ncipollo/release-action@v1
                with:
                    artifacts: "RxTelegram.Bot.${VERSION}.nupkg"
                    token: ${{ secrets.GITHUB_TOKEN }}
            -   name: Push nuget to github
                run: dotnet nuget push RxTelegram.Bot.${VERSION}.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            -   name: Push nuget to nuget.org
                uses: brandedoutcast/publish-nuget@v2.5.2
                with:
                    PROJECT_FILE_PATH: src/RxTelegram.Bot/RxTelegram.Bot.csproj
                    NUGET_KEY: ${{secrets.NUGET_API_KEY}}
