name: Publish to nuget.org
on:
  workflow_run:
    workflows: ["Check code quality"]
    branches: ["v[0-9]+.[0-9]+.[0-9]+"]
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Download build result
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: Push nuget to nuget.org
        run: dotnet nuget push RxTelegram.Bot.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
